### ISSUE TITLE
[394338] sarge is an invalid debian version?!

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#14]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87k62uvfnk.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Joseph Nahmias:

> Package: debsecan
> Version: 0.2

Can you reproduce this with debsecan 0.4.0 or later, with python-apt
installed?

If yes, I'll need your /var/lib/dpkg/status file.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20061022012332.GA1967@nahmias.net>
BTS author: joe@nahmias.net (Joseph Nahmias)

On Fri, Oct 20, 2006 at 11:30:39PM +0200, Florian Weimer wrote:
> * Joseph Nahmias:
> 
> > Package: debsecan
> > Version: 0.2
> 
> Can you reproduce this with debsecan 0.4.0 or later, with python-apt
> installed?

Just downloaded 0.4.3, and it looks like it's working properly.

Thanks,
--Joe

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <878xj8su40.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Version: 0.4.3

* Joseph Nahmias:

> On Fri, Oct 20, 2006 at 11:30:39PM +0200, Florian Weimer wrote:
>> * Joseph Nahmias:
>> 
>> > Package: debsecan
>> > Version: 0.2
>> 
>> Can you reproduce this with debsecan 0.4.0 or later, with python-apt
>> installed?
>
> Just downloaded 0.4.3, and it looks like it's working properly.

Thanks, closing the bug.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20061020191042.0E9BF1FD83@dot.nahmias.net>
BTS author: Joseph Nahmias <joe@nahmias.net>

Package: debsecan
Version: 0.2
Severity: important

joe@dot:~$ cat /etc/debian_version
3.1
joe@dot:~$ debsecan --suite sarge
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 753, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 698, in rate_system
    pkg_version = Version(contents)
  File "/usr/bin/debsecan", line 92, in __init__
    self.__parsed = self.__parse(version)
  File "/usr/bin/debsecan", line 111, in __parse
    raise ValueError, "invalid Debian version string"
ValueError: invalid Debian version string


-- System Information:
Debian Release: 3.1
Architecture: i386 (i686)
Kernel: Linux 2.4.27-2um
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)

Versions of packages debsecan depends on:
ii  python                        2.3.5-2    An interactive high-level object-o

-- no debconf information

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87k62uvfnk.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Joseph Nahmias:

> Package: debsecan
> Version: 0.2

Can you reproduce this with debsecan 0.4.0 or later, with python-apt
installed?

If yes, I'll need your /var/lib/dpkg/status file.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1GbMHZ-000311-Iz@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

# Automatically generated email from bts, devscripts version 2.9.21
tags 394338 unreproducible

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1GbMHc-000318-2M@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

# Automatically generated email from bts, devscripts version 2.9.21
tags 394338 unreproducible
