### ISSUE TITLE
[349760] debsecan: uncaught URLError exception

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#16]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1F1Zxl-00021z-1v@localhost>
BTS author: Yaroslav Halchenko <debian@onerussian.com>

Package: debsecan
Version: 0.4.0
Severity: normal

It would be useful to loop for a while (some predefined number of
cycles with predefined sleep period) to avoid malfunction due to
temporary network problems

Thank you once again for the great product

Subject: Cron <daemon@vaio> test -x /usr/bin/debsecan && /usr/bin/debsecan  --mailto root --cron
+X-Spam-Level:

Traceback (most recent call last):
  File "/usr/bin/debsecan", line 1175, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 400, in fetch_data
    u = urllib2.urlopen(r)
  File "/usr/lib/python2.3/urllib2.py", line 129, in urlopen
    return _opener.open(url, data)
  File "/usr/lib/python2.3/urllib2.py", line 326, in open
    '_open', req)
  File "/usr/lib/python2.3/urllib2.py", line 306, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.3/urllib2.py", line 901, in http_open
    return self.do_open(httplib.HTTP, req)
  File "/usr/lib/python2.3/urllib2.py", line 886, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error (-3, 'Temporary failure in name resolution')>

-- System Information:
Debian Release: testing/unstable
  APT prefers unstable
  APT policy: (600, 'unstable'), (300, 'experimental')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.15-mm1
Locale: LANG=ru_RU.KOI8-R, LC_CTYPE=ru_RU.KOI8-R (charmap=KOI8-R)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.4.67     Debian configuration management sy
ii  python                        2.3.5-3    An interactive high-level object-o

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-92  management of regular background p
ii  exim4                         4.60-2     metapackage to ease exim MTA (v4)
ii  exim4-daemon-light [mail-tran 4.60-2     lightweight exim MTA (v4) daemon

-- debconf information:
  debsecan/suite: GENERIC
  debsecan/report: true


--Yarik

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87oe20xwmo.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Yaroslav Halchenko:

> It would be useful to loop for a while (some predefined number of
> cycles with predefined sleep period) to avoid malfunction due to
> temporary network problems

Thanks for the report.  In the default installation, debsecan retries
every hour anyway (until it has retrieved the data for that day), it's
not really necessary to retry in debsecan itself.

But it certainly makes sense to suppress the error message when
running in cron mode.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87zmlkwgan.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Version: 0.4.1

The bug number in the upload was wrong.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A log time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
