### ISSUE TITLE
[345308] debsecan: crash when getting an error 403 from the web server

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#31]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87wthm4x9o.fsf@wide.bouthors.org>
BTS author: Cyril Bouthors <cyril@bouthors.org>

Package: debsecan
Version: 0.3.3
Severity: important

debsecan seems to crash when it gets an error 403 from the web server:

root@wide:~# debsecan --only-fixed --suite sid
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 889, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 345, in fetch_data
    data = StringIO(zlib.decompress(''.join(data)))
zlib.error: Error -3 while decompressing data: incorrect header check
root@wide:~#

-- System Information:
Debian Release: testing/unstable
  APT prefers unstable
  APT policy: (500, 'unstable'), (500, 'stable')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.15-rc5-686
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.4.61     Debian configuration management sy
ii  python                        2.3.5-3    An interactive high-level object-o

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-92  management of regular background p
ii  exim4                         4.60-1     metapackage to ease exim MTA (v4)
ii  exim4-daemon-light [mail-tran 4.60-1     lightweight exim MTA (v4) daemon

-- debconf information:
* debsecan/suite: sid
  debsecan/report: true

-- 
Cyril Bouthors

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1EtBHC-0004fx-Af@spohr.debian.org>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Source: debsecan
Source-Version: 0.3.4

We believe that the bug you reported is fixed in the latest version of
debsecan, which is due to be installed in the Debian FTP archive:

debsecan_0.3.4.dsc
  to pool/main/d/debsecan/debsecan_0.3.4.dsc
debsecan_0.3.4.tar.gz
  to pool/main/d/debsecan/debsecan_0.3.4.tar.gz
debsecan_0.3.4_all.deb
  to pool/main/d/debsecan/debsecan_0.3.4_all.deb



A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 345308@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Florian Weimer <fw@deneb.enyo.de> (supplier of updated debsecan package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.7
Date: Sun,  1 Jan 2006 13:50:24 +0100
Source: debsecan
Binary: debsecan
Architecture: source all
Version: 0.3.4
Distribution: unstable
Urgency: low
Maintainer: Florian Weimer <fw@deneb.enyo.de>
Changed-By: Florian Weimer <fw@deneb.enyo.de>
Description: 
 debsecan   - Debian Security Analyzer
Closes: 345308
Changes: 
 debsecan (0.3.4) unstable; urgency=low
 .
   * Switch to urllib2, which handles HTTP errors in a better way.
     Closes: #345308.
   * Add --no-obsolete option.
Files: 
 e8a9e90a44330ee367573e00ce512d15 787 admin optional debsecan_0.3.4.dsc
 f6f3b137dd90c423be21f5eabac6bc6c 52509 admin optional debsecan_0.3.4.tar.gz
 13e30378e4d90b9895f4d3595e39f3a0 16696 admin optional debsecan_0.3.4_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.1 (GNU/Linux)

iQEVAwUBQ7hNt797/wQC1SS+AQL5+gf+Nwn6LHFawi/zJWW49gadsJpACzOcGRyn
VZtppFV9F9QK+I1V8ouiqnHzktSKWarkjhovwLxF/Sx9r2iaEeDzRrAsUxKC/S1x
QXdLhuYVmYxtQXaoAV5G6wBpxwIo4lgtkYFrDaS08/QFja9PwewLfm4khtnf9SIC
UcQFQKQH4skqUK3+ESqIOSmj/hwhG5JGVeXNjOq0DEIUTHpm8o9DPTg5nLMlRk2+
wgcocTvxxhFJ7lWbXF4RVdkeVcGLLzJ3ShCSc9zEJYm5WHXlEomYI8Uj0EvKolvs
+P+MHSosgyoJXuykMGfU7O9KkguauUZQxeJydnpSDMteqbVEPEYJsw==
=cGc9
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A log time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
