### ISSUE TITLE
[435795] debsecan: allow tilde (~) in package versions

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#50]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20070803083210.10910.3043.reportbug@treasure.calvinsplayground.de>
BTS author: Bastian Kleineidam <calvin@debian.org>

Package: debsecan
Version: 0.4.9
Severity: normal
Tags: patch

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

this morning I received error messages from the debsecan cron job:
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 1356, in ?
    rate_system(target, options, fetch_data(options, config), history)
  File "/usr/bin/debsecan", line 1333, in rate_system
    if v.is_vulnerable (bp, sp):
  File "/usr/bin/debsecan", line 483, in is_vulnerable
    self._parse()
  File "/usr/bin/debsecan", line 515, in _parse
    self.unstable_version = Version(self.unstable_version)
  File "/usr/bin/debsecan", line 93, in __init__
    self.__parsed = self.__parse(version)
  File "/usr/bin/debsecan", line 112, in __parse
    raise ValueError, "invalid Debian version string"
ValueError: invalid Debian version string

It turned out that a version with '~' in it caused the error.

Here is a patch that allows '~' in the version string, which is compatible
with the algorithm mention in [1].
[1] http://lists.debian.org/debian-devel-announce/2006/08/msg00006.html

Regards,
  Bastian

- -- System Information:
Debian Release: lenny/sid
  APT prefers unstable
  APT policy: (500, 'unstable')
Architecture: i386 (i686)

Kernel: Linux 2.6.22-ck1treasure1 (PREEMPT)
Locale: LANG=de_DE@euro, LC_CTYPE=de_DE@euro (charmap=ISO-8859-15)
Shell: /bin/sh linked to /bin/bash

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.5.14     Debian configuration management sy
ii  python                        2.4.4-6    An interactive high-level object-o
ii  python-apt                    0.7.3      Python interface to libapt-pkg

Versions of packages debsecan recommends:
ii  cron                3.0pl1-100           management of regular background p
ii  qmail-run [mail-tra 1.03+calvin-0calvin3 Secure, reliable, efficient, simpl

- -- debconf-show failed

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.6 (GNU/Linux)

iD8DBQFGsugKeBwlBDLsbz4RAsWMAJkBprf8XdfulXEf5Hoa+5TT13noqgCeL1vE
yj5J2Yvhyjehy1oPHSP0ynk=
=M4cJ
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87r6mkicvs.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Bastian Kleineidam:

> Package: debsecan
> Version: 0.4.9

This version has got a dependency on python-apt, and if this package
is installed (and the Python module it provides can be imported),
debsecan can handle ~ version numbers.  (If python-apt can be
installed without properly working, it's likely that its dependencies
are broken.)

> Here is a patch that allows '~' in the version string, which is compatible
> with the algorithm mention in [1].
> [1] http://lists.debian.org/debian-devel-announce/2006/08/msg00006.html

This may be the case, but according to my testing, this is not the
algorithm used by APT.  For instance, your patch causes 1.0 to sort
before 1.0-~0, but the other way round is correct as far as APT is
concerned.

This is not your fault.  The Version class was implemented based on
the description in the Policy, and the algorithm described there does
not match what APT and dpkg actually do.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87d4xjgx5r.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Florian Weimer:

> * Bastian Kleineidam:
>
>> Package: debsecan
>> Version: 0.4.9
>
> This version has got a dependency on python-apt, and if this package
> is installed (and the Python module it provides can be imported),
> debsecan can handle ~ version numbers.  (If python-apt can be
> installed without properly working, it's likely that its dependencies
> are broken.)

Can you still reproduce this bug?

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1IMq7K-0003WM-Kq@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

# Automatically generated email from bts, devscripts version 2.10.7
tags 435795 unreproducible

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1IMq8i-0003Y3-1Y@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

# Automatically generated email from bts, devscripts version 2.10.7
tags 435795 - patch

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <200708201915.46364.calvin@debian.org>
BTS author: Bastian Kleineidam <calvin@debian.org>

Hello Florian,

Am Sonntag, 19. August 2007 21:08:16 schrieben Sie:
> * Florian Weimer:
> > * Bastian Kleineidam:
> >> Package: debsecan
> >> Version: 0.4.9
> >
> > This version has got a dependency on python-apt, and if this package
> > is installed (and the Python module it provides can be imported),
> > debsecan can handle ~ version numbers.  (If python-apt can be
> > installed without properly working, it's likely that its dependencies
> > are broken.)
>
> Can you still reproduce this bug?

No, the python-apt package is not broken any more, so debsecan is also working 
properly again. As you already said the problem really was the python-apt 
breakage, but I did not notice that until I dug into the code because the 
version comparison fallback code threw errors.

If you depend on python-apt anyway, I suggest removing the version compare 
fallback code. I think it is better to clearly propagate any python-apt 
problem instead of using code which has to be maintained and fixed separately 
from apt development.


Regards,
  Bastian

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87lkc65crd.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Bastian Kleineidam:

> If you depend on python-apt anyway, I suggest removing the version compare 
> fallback code. I think it is better to clearly propagate any python-apt 
> problem instead of using code which has to be maintained and fixed separately 
> from apt development.

Yes, I agree, it's probably about time to remove that fallback code.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1INBFn-0006dr-MR@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

# Automatically generated email from bts, devscripts version 2.10.7
tags 435795 pending

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1IRsMl-0000zH-BG@ries.debian.org>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Source: debsecan
Source-Version: 0.4.10

We believe that the bug you reported is fixed in the latest version of
debsecan, which is due to be installed in the Debian FTP archive:

debsecan_0.4.10.dsc
  to pool/main/d/debsecan/debsecan_0.4.10.dsc
debsecan_0.4.10.tar.gz
  to pool/main/d/debsecan/debsecan_0.4.10.tar.gz
debsecan_0.4.10_all.deb
  to pool/main/d/debsecan/debsecan_0.4.10_all.deb



A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 435795@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Florian Weimer <fw@deneb.enyo.de> (supplier of updated debsecan package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.7
Date: Sun, 02 Sep 2007 17:27:52 +0200
Source: debsecan
Binary: debsecan
Architecture: source all
Version: 0.4.10
Distribution: unstable
Urgency: low
Maintainer: Florian Weimer <fw@deneb.enyo.de>
Changed-By: Florian Weimer <fw@deneb.enyo.de>
Description: 
 debsecan   - Debian Security Analyzer
Closes: 422997 433728 435791 435795 437632 437762
Changes: 
 debsecan (0.4.10) unstable; urgency=low
 .
   * Support macros in MAILTO configuration variable
     Closes: #433728.
   * Make subject line configurable through /etc/default/debsecan.
     Closes: #437762.
   * Remove support for running without python-apt installed.
     This produces more useful error messages in case python-apt is
     installed, but unusable.  Closes: #435795.
   * Document how to reduce the freqency of reports.  Closes: #422997.
   * Add Brazilian Portuguese debconf templates translation,
     by Eder L. Marques  <frolic@debian-ce.org>.  Closes: #437632.
   * Set MAILTO=root in generated cron file.  This change is only effective
     on new installations.  Suggested by Bastian Kleineidam.
     Closes: #435791.
Files: 
 131b3e3cebbdfc47b9e5657d59fc9376 821 admin optional debsecan_0.4.10.dsc
 c75bd8394280aebece1eadd54341774a 83002 admin optional debsecan_0.4.10.tar.gz
 9b4597ac07264f0e45a019e5f3863a4f 32358 admin optional debsecan_0.4.10_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.6 (GNU/Linux)

iQEVAwUBRtrivb97/wQC1SS+AQLV4ggAjZMr09srr99RYnUsdGAbQf36uDJnL2jn
8YPGDmoM01SNzusr1Hs5xfy/BjqzdUxGi2UMuTxYffp5X0bqV7idVMlA2pffM+r2
o8umR1sXaXqwaDuJRvNaCX+7fO2SK3jDVKiImRi518hlpkyQC6VglpepELrjYDeT
hk5EvyRlvpGkQSx2uQU9hb0jB3zmZL2EMLb0QcbSn0dy2oGPex8whQThCICcEgCe
70oGhJLkVNE5sBYNHBoUfkFvGq+nwdELdb7drdUwNwCdIyrRFo/0aEHFB9fJ/Wcp
YAppFPR22uWyIjwswL4au0TqqqiAO2oxtph+OSoaE19WOi+SPQZFqA==
=BokB
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A log time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
