### ISSUE TITLE
[390596] debsecan: Recommend upgrading 'python-apt' from Suggests to Depends

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#66]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20061002023219.27248.87488.reportbug@walkies.ewhac.org>
BTS author: "Leo L. Schwab" <ewhac@best.com>

Package: debsecan
Version: 0.4.2
Severity: important

	For the last couple of days, I've noticed the 'debsecan' cron
job bombing out, with the following message mailed to me:

    ----
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 753, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 698, in rate_system
    pkg_version = Version(contents)
  File "/usr/bin/debsecan", line 92, in __init__
    self.__parsed = self.__parse(version)
  File "/usr/bin/debsecan", line 111, in __parse
    raise ValueError, "invalid Debian version string"
ValueError: invalid Debian version string
    ----

	This started happening shortly after I upgraded the system from
Python 2.3 to 2.4.  After running 'debsecan' by hand, I noticed a tiny
diagnostic (not included in the emailed output) suggesting that
installing 'python-apt' would be helpful.  I did, and the problem
immediately went away.

	Checking with 'aptitude', I see that 'debsecan' merely Suggests
'python-apt', and does not Depend on it, thus resulting in the unhelpful
output.  Barring other considerations, I would recommend upgrading
'python-apt' to a Dependency and not simply a Suggestion.  Either that,
or fixing 'debsecan' such that it doesn't bomb out completely if
'python-apt' isn't present.

					Schwab


-- System Information:
Debian Release: testing/unstable
  APT prefers unstable
  APT policy: (500, 'unstable'), (500, 'testing'), (500, 'stable')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.17
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.5.5      Debian configuration management sy
ii  python                        2.4.3-11   An interactive high-level object-o

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-93  management of regular background p
ii  exim [mail-transport-agent]   3.36-18    An MTA (Mail Transport Agent)

-- debconf information:
  debsecan/report: true
  debsecan/suite: GENERIC

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87zmcepq96.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

severity 390596
tags 390596 confirmed
thanks

* Leo L. Schwab:

> 	For the last couple of days, I've noticed the 'debsecan' cron
> job bombing out, with the following message mailed to me:

Yeah, we really need to support those ~ versions.  Adding a dependency
on python-apt seems the way to go, since there isn't a separate
specification of the ~ semantics (as far as I know).

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1GUTBQ-0004bQ-4k@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

# Automatically generated email from bts, devscripts version 2.9.21
severity 390596 grave

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1GUVfM-0000Vv-Jp@spohr.debian.org>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Source: debsecan
Source-Version: 0.4.3

We believe that the bug you reported is fixed in the latest version of
debsecan, which is due to be installed in the Debian FTP archive:

debsecan_0.4.3.dsc
  to pool/main/d/debsecan/debsecan_0.4.3.dsc
debsecan_0.4.3.tar.gz
  to pool/main/d/debsecan/debsecan_0.4.3.tar.gz
debsecan_0.4.3_all.deb
  to pool/main/d/debsecan/debsecan_0.4.3_all.deb



A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 390596@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Florian Weimer <fw@deneb.enyo.de> (supplier of updated debsecan package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.7
Date: Mon,  2 Oct 2006 19:46:10 +0200
Source: debsecan
Binary: debsecan
Architecture: source all
Version: 0.4.3
Distribution: unstable
Urgency: low
Maintainer: Florian Weimer <fw@deneb.enyo.de>
Changed-By: Florian Weimer <fw@deneb.enyo.de>
Description: 
 debsecan   - Debian Security Analyzer
Closes: 368376 369098 376773 387520 390596
Changes: 
 debsecan (0.4.3) unstable; urgency=low
 .
   * Correct spelling error in manpage.  Closes: #368376.
   * Promote python-apt to a full dependency.  Package versions containing
     the ~ characters lack a clear specification, and reusing the existing
     implementation in APT is the best way to deal with this issue.
     Closes: #390596.
   * Document the http_proxy environment variable.  Closes: #376773.
   * Add Czech translation of debconf messages, by Miroslav Kure
     <kurem@upcase.inf.upol.cz>.  Closes: #369098.
   * Add Swedish translation of debconf message, by Daniel Nylander
     <yeager@lidkoping.net>.  Closes: #387520.
Files: 
 8b6a29a78df2b4816262ce3795e93904 820 admin optional debsecan_0.4.3.dsc
 fb931f1776685120a07a0de61b20ba8f 285545 admin optional debsecan_0.4.3.tar.gz
 ea629f7a9a8e1832f2eb59ebae131f1c 21766 admin optional debsecan_0.4.3_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.5 (GNU/Linux)

iQEVAwUBRSFe8b97/wQC1SS+AQLWJggAmxhwZqZn85Xv9CKY2NhtimmazKwpI9v1
BQkqtH1mc2rpRy3xdYLNdzlL0Lz3nkXKePak98PIvlDhcVEXpQEvB1joAeiyUmfy
nMhHC+BJ3Bpe4fJBy0/ec1CyhpZnyYPKjwkSDsx1KsZuGL4QspB/W6Gx79pQJ/0g
vNlufPCWrusoO6irGsmvMU2Xhr4FX3RX++EwhhdW+K4H6xX6f3CuVeShdyIVuSNB
XbCninosyJN0y/zn30j8EsT9LnALWOISBlEwghYLu030mEjyWIXq2pRg+H7R/Re9
1pfIkJ/x7LcZFJTodvfyjR/hhKbt1Qn96d4/HVpLEFq6Q2qC5qlsyw==
=Jgck
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A log time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
