### ISSUE TITLE
[390596] debsecan: Recommend upgrading 'python-apt' from Suggests to Depends

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#66]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20061002023219.27248.87488.reportbug@walkies.ewhac.org>
BTS author: "Leo L. Schwab" <ewhac@best.com>

Package: debsecan
Version: 0.4.2
Severity: important

	For the last couple of days, I've noticed the 'debsecan' cron
job bombing out, with the following message mailed to me:

    ----
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 753, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 698, in rate_system
    pkg_version = Version(contents)
  File "/usr/bin/debsecan", line 92, in __init__
    self.__parsed = self.__parse(version)
  File "/usr/bin/debsecan", line 111, in __parse
    raise ValueError, "invalid Debian version string"
ValueError: invalid Debian version string
    ----

	This started happening shortly after I upgraded the system from
Python 2.3 to 2.4.  After running 'debsecan' by hand, I noticed a tiny
diagnostic (not included in the emailed output) suggesting that
installing 'python-apt' would be helpful.  I did, and the problem
immediately went away.

	Checking with 'aptitude', I see that 'debsecan' merely Suggests
'python-apt', and does not Depend on it, thus resulting in the unhelpful
output.  Barring other considerations, I would recommend upgrading
'python-apt' to a Dependency and not simply a Suggestion.  Either that,
or fixing 'debsecan' such that it doesn't bomb out completely if
'python-apt' isn't present.

					Schwab


-- System Information:
Debian Release: testing/unstable
  APT prefers unstable
  APT policy: (500, 'unstable'), (500, 'testing'), (500, 'stable')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.17
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.5.5      Debian configuration management sy
ii  python                        2.4.3-11   An interactive high-level object-o

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-93  management of regular background p
ii  exim [mail-transport-agent]   3.36-18    An MTA (Mail Transport Agent)

-- debconf information:
  debsecan/report: true
  debsecan/suite: GENERIC

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20061002023219.27248.87488.reportbug@walkies.ewhac.org>
BTS author: "Leo L. Schwab" <ewhac@best.com>

Package: debsecan
Version: 0.4.2
Severity: important

	For the last couple of days, I've noticed the 'debsecan' cron
job bombing out, with the following message mailed to me:

    ----
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 753, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 698, in rate_system
    pkg_version = Version(contents)
  File "/usr/bin/debsecan", line 92, in __init__
    self.__parsed = self.__parse(version)
  File "/usr/bin/debsecan", line 111, in __parse
    raise ValueError, "invalid Debian version string"
ValueError: invalid Debian version string
    ----

	This started happening shortly after I upgraded the system from
Python 2.3 to 2.4.  After running 'debsecan' by hand, I noticed a tiny
diagnostic (not included in the emailed output) suggesting that
installing 'python-apt' would be helpful.  I did, and the problem
immediately went away.

	Checking with 'aptitude', I see that 'debsecan' merely Suggests
'python-apt', and does not Depend on it, thus resulting in the unhelpful
output.  Barring other considerations, I would recommend upgrading
'python-apt' to a Dependency and not simply a Suggestion.  Either that,
or fixing 'debsecan' such that it doesn't bomb out completely if
'python-apt' isn't present.

					Schwab


-- System Information:
Debian Release: testing/unstable
  APT prefers unstable
  APT policy: (500, 'unstable'), (500, 'testing'), (500, 'stable')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.17
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.5.5      Debian configuration management sy
ii  python                        2.4.3-11   An interactive high-level object-o

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-93  management of regular background p
ii  exim [mail-transport-agent]   3.36-18    An MTA (Mail Transport Agent)

-- debconf information:
  debsecan/report: true
  debsecan/suite: GENERIC
