### ISSUE TITLE
[344996] debsecan: ugly emails every hour

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#67]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20051228105333.27209.9760.reportbug@magla.zg.iskon.hr>
BTS author: Zlatko Calusic <zlatko.calusic@iskon.hr>

Package: debsecan
Version: 0.3.2
Severity: normal

I'm getting emails like this every hour:

Traceback (most recent call last):
  File "/usr/bin/debsecan", line 875, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 798, in rate_system
    for pkg in packages:
  File "/usr/bin/debsecan", line 175, in __iter__
    self.raiseSyntaxError("expected package field")
  File "/usr/bin/debsecan", line 197, in raiseSyntaxError
    raise ParseError(self.name, lineno, msg)
__main__.ParseError: expected package field

Please fix it. Thanks!

-- System Information:
Debian Release: testing/unstable
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.14
Locale: LANG=C, LC_CTYPE=hr_HR (charmap=ISO-8859-2)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.4.66     Debian configuration management sy
ii  python                        2.3.5-3    An interactive high-level object-o

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-92  management of regular background p
ii  equivs-dummy [mail-transport- 2005-04-16 Dummy package

-- debconf information:
* debsecan/suite: sid
  debsecan/report: true

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <8764p9pis4.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Zlatko Calusic:

> Package: debsecan
> Version: 0.3.2
> Severity: normal
>
> I'm getting emails like this every hour:
>
> Traceback (most recent call last):
>   File "/usr/bin/debsecan", line 875, in ?
>     rate_system(target, options, fetch_data(options), history)
>   File "/usr/bin/debsecan", line 798, in rate_system
>     for pkg in packages:
>   File "/usr/bin/debsecan", line 175, in __iter__
>     self.raiseSyntaxError("expected package field")
>   File "/usr/bin/debsecan", line 197, in raiseSyntaxError
>     raise ParseError(self.name, lineno, msg)
> __main__.ParseError: expected package field
>
> Please fix it. Thanks!

This means that your /var/lib/dpkg/status file contains some invalid
data.  I'll investigate it if you can send mee a compressed copy.

In the meantime, you can invoke "dpkg-reconfigure debsecan" and answer
"No" to the first question.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <dnzmmlv483.fsf@magla.zg.iskon.hr>
BTS author: Zlatko Calusic <zlatko.calusic@iskon.hr>

Florian Weimer <fw@deneb.enyo.de> writes:

> * Zlatko Calusic:
>
>> Package: debsecan
>> Version: 0.3.2
>> Severity: normal
>>
>> I'm getting emails like this every hour:
>>
>> Traceback (most recent call last):
>>   File "/usr/bin/debsecan", line 875, in ?
>>     rate_system(target, options, fetch_data(options), history)
>>   File "/usr/bin/debsecan", line 798, in rate_system
>>     for pkg in packages:
>>   File "/usr/bin/debsecan", line 175, in __iter__
>>     self.raiseSyntaxError("expected package field")
>>   File "/usr/bin/debsecan", line 197, in raiseSyntaxError
>>     raise ParseError(self.name, lineno, msg)
>> __main__.ParseError: expected package field
>>
>> Please fix it. Thanks!

Hey Florian, thanks for a real fast reply!

>
> This means that your /var/lib/dpkg/status file contains some invalid
> data.  I'll investigate it if you can send mee a compressed copy.

Interesting, I'll send you a copy off-list to help you debug it, sure.

>
> In the meantime, you can invoke "dpkg-reconfigure debsecan" and answer
> "No" to the first question.
>

Right, that should do it. Although I could swear that I have answered
that question as 'no' before, but who knows what happened, I've seen
much nastier bugs... :)

My status file is on your way, hopefully it gives you some idea what's
goin' on...

Regards,
-- 
Zlatko

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87mzilo1z0.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

tag 344996 confirmed
thanks

* Zlatko Calusic:

>> This means that your /var/lib/dpkg/status file contains some invalid
>> data.  I'll investigate it if you can send mee a compressed copy.
>
> Interesting, I'll send you a copy off-list to help you debug it, sure.

The culprit is:

Package: nerolinux
Status: install ok installed
Priority: optional
Section: unknown
Maintainer: Nero AG
Architecture: i386
Version: 2.0.0.4-2
Depends: libc6 (>= 2.2.4-4), libglib1.2 (>= 1.2.0), libgtk1.2 (>= 1.2.10-4), xlibs (>= 4.1.0)
Description: NeroLINUX CD/DVD Burning Software
 Copyright: Nero AG
 
 NeroLINUX uses Nero 6.6's embedded API to bring Nero's powerful CD/DVD-writer
 functions to the Linux Desktop.

The line " \n" in the description is wrong, it should read " .\n".
I'm going to implement a workaround in debsecan, even though this
begins to resemble HTML parsing. 8-(

> Right, that should do it. Although I could swear that I have answered
> that question as 'no' before, but who knows what happened, I've seen
> much nastier bugs... :)

The question is a low-priority debconf question, and it was introduced
in version 0.3.2.  Unless you explicitly ran dpkg-reconfigure, you
shouldn't have seen it before.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1Erf9g-0000xQ-Qf@spohr.debian.org>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Source: debsecan
Source-Version: 0.3.3

We believe that the bug you reported is fixed in the latest version of
debsecan, which is due to be installed in the Debian FTP archive:

debsecan_0.3.3.dsc
  to pool/main/d/debsecan/debsecan_0.3.3.dsc
debsecan_0.3.3.tar.gz
  to pool/main/d/debsecan/debsecan_0.3.3.tar.gz
debsecan_0.3.3_all.deb
  to pool/main/d/debsecan/debsecan_0.3.3_all.deb



A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 344996@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Florian Weimer <fw@deneb.enyo.de> (supplier of updated debsecan package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.7
Date: Wed, 28 Dec 2005 09:52:53 +0100
Source: debsecan
Binary: debsecan
Architecture: source all
Version: 0.3.3
Distribution: unstable
Urgency: low
Maintainer: Florian Weimer <fw@deneb.enyo.de>
Changed-By: Florian Weimer <fw@deneb.enyo.de>
Description: 
 debsecan   - Debian Security Analyzer
Closes: 344976 344996
Changes: 
 debsecan (0.3.3) unstable; urgency=low
 .
   * Fix syntax error in config script.  Closes: #344976.
   * Be more tolerant about broken package descriptions in
     /var/lib/dpkg/status.  Closes: #344996.
Files: 
 2e314762dac92bb55d85e6cbdcc49232 787 admin optional debsecan_0.3.3.dsc
 6b977db9b9430d890729f1fdff673cb6 50236 admin optional debsecan_0.3.3.tar.gz
 8adfc6a6f6cbee64efaed5b454568bf5 16306 admin optional debsecan_0.3.3_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.1 (GNU/Linux)

iQEVAwUBQ7LJgr97/wQC1SS+AQLFWgf/ZjQjUmTKlP/BWixGrT9YIjGSQUF0GTdg
X//9/CDsIGTCb8LOXE0m20rI2b4ed5EtNyt0QM5MiuGcR9uoyVJi6jxw05gg7gKj
ho50Cx3rn4f1xaFasHtE1hT3LTBUiHXezfCvEj6oVhy19SPwVB20StDZFbwaaGeN
9JCcdC0thzIKvORYcat+XwJAafJSKQkvWQXIUkRyjlZ/MwaIFEENzM1CmHqFODoE
TXmXGOsmPDo+6F6JRiFZepM6SuhUsKlVQtXd0pTR8fZ8SSS9dKdEu9AceeG8p8cD
m7RMnbHOyg3rRj7C4fmD0ToNrCDmkWaaWPpIFB2Q9J3h/CpWKdTtoA==
=upUm
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20060206215624.23758.23236.reportbug@gpk.lan>
BTS author: Greg Kochanski <gpk@kochanski.org>

Package: debsecan
Version: 0.3.4
Followup-For: Bug #344996


I see this:

Feb  6 21:32:01 gpk /USR/SBIN/CRON[21289]: (daemon) CMD (test -x /usr/bin/debsecan && /usr/bin/debsecan  --mailto root --cron)

after this:

$ sudo apt-get remove debsecan
Reading package lists... Done
Building dependency tree... Done
Package debsecan is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$

-- System Information:
Debian Release: testing/unstable
  APT prefers testing
  APT policy: (500, 'testing')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.12-1-686
Locale: LANG=en_GB, LC_CTYPE=en_GB (charmap=ISO-8859-1)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.4.67     Debian configuration management sy
ii  python                        2.3.5-5    An interactive high-level object-o

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-92  management of regular background p
ii  exim4                         4.60-3     metapackage to ease exim MTA (v4) 
ii  exim4-daemon-light [mail-tran 4.60-3     lightweight exim MTA (v4) daemon

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87vevsruuq.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Greg Kochanski:

> I see this:
>
> Feb  6 21:32:01 gpk /USR/SBIN/CRON[21289]: (daemon) CMD (test -x /usr/bin/debsecan && /usr/bin/debsecan  --mailto root --cron)

But I hope you don't receive any funny email messages.

> after this:
>
> $ sudo apt-get remove debsecan
> Reading package lists... Done
> Building dependency tree... Done
> Package debsecan is not installed, so not removed
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> $

Have you tried dpkg --purge?

Technically, the cronjob is treated as a configuration file, and it's
only removed during purge.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <871wyeazpq.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Greg Kochanski:

>> Technically, the cronjob is treated as a configuration file, and
>> it's only removed during purge.

> That sounds like a bad thing, and I've run across that before.
> Is that Debian policy?

Sort of.  The treatment of configuration files is the reason why there
is both dpkg --remove and dpkg --purge.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87fy93scmf.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

As far as I can tell, the cron entry is properly deactivated when the
binary is deinstalled (using the "test -x &&" idiom).  As I perviously
wrote, you need to purge the package if you want to remove all
configuration files.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87fy91ew4m.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

close 344996 0.4.4
thanks

This version installs a proper crontab.  (My previous attempt
to tell the BTS about this failed.)

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A log time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
