### ISSUE TITLE
[344117] bad permissions on /var/lib/debsecan

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#87]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <1135062147.6577.37.camel@localhost.localdomain>
BTS author: Paul Wise <pabs3@bonedaddy.net>

Package: debsecan
Version: 0.2
Severity: important

I installed the debsecan cron job and then manually ran the command in
the crontab, giving this error:

chianamo:~# su daemon -c '/usr/bin/debsecan --suite sid --mailto root --cron'
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 753, in ?
    rate_system(target, options, fetch_data(options), history)
  File "/usr/bin/debsecan", line 738, in rate_system
    formatter.finish()
  File "/usr/bin/debsecan", line 631, in finish
    self._write_history(self.options.history)
  File "/usr/bin/debsecan", line 508, in _write_history
    f = file(new_name, "w+")
IOError: [Errno 13] Permission denied: '/var/lib/debsecan/history.new'

Permissions are:

chianamo:~# ls -ld /var/lib/debsecan/
drwxr-xr-x 2 root root 48 2005-12-20 03:38 /var/lib/debsecan/

This means that the default crontab will not work. Please fix the
permissions on /var/lib/debsecan/.

-- System Information:
Debian Release: unstable
  APT prefers unstable
  APT policy: (500, 'unstable'), (1, 'experimental')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.14-1-k7
Locale: LANG=en_AU.UTF-8, LC_CTYPE=en_AU.UTF-8 (charmap=UTF-8)

Versions of packages debsecan depends on:
ii  python                        2.3.5-3    An interactive high-level object-o

-- 
bye,
pabs

http://wiki.debian.org/PaulWise

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1Eoemv-0002k5-A8@spohr.debian.org>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Source: debsecan
Source-Version: 0.2.1

We believe that the bug you reported is fixed in the latest version of
debsecan, which is due to be installed in the Debian FTP archive:

debsecan_0.2.1.dsc
  to pool/main/d/debsecan/debsecan_0.2.1.dsc
debsecan_0.2.1.tar.gz
  to pool/main/d/debsecan/debsecan_0.2.1.tar.gz
debsecan_0.2.1_all.deb
  to pool/main/d/debsecan/debsecan_0.2.1_all.deb



A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 344117@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Florian Weimer <fw@deneb.enyo.de> (supplier of updated debsecan package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.7
Date: Tue, 20 Dec 2005 11:17:28 +0100
Source: debsecan
Binary: debsecan
Architecture: source all
Version: 0.2.1
Distribution: unstable
Urgency: low
Maintainer: Florian Weimer <fw@deneb.enyo.de>
Changed-By: Florian Weimer <fw@deneb.enyo.de>
Description: 
 debsecan   - Debian Security Analyzer
Closes: 344117
Changes: 
 debsecan (0.2.1) unstable; urgency=low
 .
   * Fix permissions of /var/lib/debsecan.  Closes: #344117.
Files: 
 07f25e3c7a47dbab95ec27e553037c1f 787 admin optional debsecan_0.2.1.dsc
 0e932478d7967e4e5a4e5ad2a2edde1c 30569 admin optional debsecan_0.2.1.tar.gz
 0d4da973cc4a86c1165f2adefcb064ab 13200 admin optional debsecan_0.2.1_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.1 (GNU/Linux)

iQEVAwUBQ6faer97/wQC1SS+AQJTngf+OeMtKp7ycGGb/NGWKDuGqqvbzyIUl7Mq
yyA8dmFusaHrATST2horocFSolcVlVTkOtMc+9R7BCYhS7xvhNatBb5X0S/UVA6I
9wXHMCILKzahx0fDjY++BGemrUTCOrV4YFnx1lMWG9Yrx/Dk51W1AxOjHCsWtQv6
0sF+WkHdkduT9afvxiLBxEtt6WVS21qRkx3EAgoWAQ0H6aDAm2A/uRv5Pa/xtOUk
Wc89zmKxwc5+8NfbFVVAS0L4xCbB/jOh2QWMkkNAPBVp7D/tR4nKvvKMwdkD0Qso
HPXlHXcaTno+OtgPIv0cbunNWvcbMo68I8cUXzbX0GOzGjvxpwmucw==
=mFlY
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <1170490521.7429.34.camel@chianamo>
BTS author: Paul Wise <pabs@debian.org>

owner 215367 !
owner 282313 !
owner 308433 !
owner 322688 !
owner 337074 !
owner 378112 !
submitter 195121 !
submitter 226101 !
submitter 240595 !
submitter 240601 !
submitter 267243 !
submitter 267372 !
submitter 282313 !
submitter 283958 !
submitter 284711 !
submitter 286177 !
submitter 288165 !
submitter 290457 !
submitter 296114 !
submitter 296588 !
submitter 297321 !
submitter 298842 !
submitter 303093 !
submitter 306287 !
submitter 306290 !
submitter 306752 !
submitter 311535 !
submitter 312058 !
submitter 312288 !
submitter 312289 !
submitter 314215 !
submitter 314746 !
submitter 316331 !
submitter 316895 !
submitter 317855 !
submitter 318712 !
submitter 318773 !
submitter 318898 !
submitter 319317 !
submitter 319447 !
submitter 319837 !
submitter 320127 !
submitter 320287 !
submitter 320294 !
submitter 320431 !
submitter 320432 !
submitter 321274 !
submitter 321572 !
submitter 321908 !
submitter 321911 !
submitter 322663 !
submitter 322688 !
submitter 322698 !
submitter 323509 !
submitter 323529 !
submitter 323556 !
submitter 323943 !
submitter 324089 !
submitter 324214 !
submitter 324950 !
submitter 326868 !
submitter 327431 !
submitter 328216 !
submitter 328217 !
submitter 329047 !
submitter 329072 !
submitter 329171 !
submitter 329176 !
submitter 329889 !
submitter 329925 !
submitter 330480 !
submitter 331040 !
submitter 331176 !
submitter 331601 !
submitter 332930 !
submitter 332938 !
submitter 333331 !
submitter 333642 !
submitter 333757 !
submitter 335648 !
submitter 336149 !
submitter 336589 !
submitter 337074 !
submitter 337477 !
submitter 337516 !
submitter 337518 !
submitter 337975 !
submitter 338098 !
submitter 338415 !
submitter 339582 !
submitter 340265 !
submitter 340550 !
submitter 340551 !
submitter 340782 !
submitter 340798 !
submitter 340802 !
submitter 340830 !
submitter 340831 !
submitter 340832 !
submitter 341417 !
submitter 342192 !
submitter 343137 !
submitter 343403 !
submitter 343870 !
submitter 344117 !
submitter 345617 !
submitter 347200 !
submitter 347202 !
submitter 347510 !
submitter 347687 !
submitter 348029 !
submitter 348448 !
submitter 348494 !
submitter 349647 !
submitter 350972 !
submitter 350973 !
submitter 350974 !
submitter 350975 !
submitter 350976 !
submitter 351019 !
submitter 351372 !
submitter 352009 !
submitter 353251 !
submitter 353665 !
submitter 353734 !
submitter 353818 !
submitter 354763 !
submitter 354931 !
submitter 355083 !
submitter 355358 !
submitter 355537 !
submitter 355613 !
submitter 355666 !
submitter 355957 !
submitter 356652 !
submitter 356653 !
submitter 356668 !
submitter 356978 !
submitter 357610 !
submitter 358599 !
submitter 358795 !
submitter 358815 !
submitter 358966 !
submitter 359049 !
submitter 359353 !
submitter 360305 !
submitter 362694 !
submitter 363243 !
submitter 363244 !
submitter 363247 !
submitter 363453 !
submitter 364841 !
submitter 364843 !
submitter 364846 !
submitter 364851 !
submitter 364854 !
submitter 364901 !
submitter 365133 !
submitter 365141 !
submitter 365299 !
submitter 365479 !
submitter 365680 !
submitter 365965 !
submitter 365966 !
submitter 367048 !
submitter 368158 !
submitter 368733 !
submitter 368810 !
submitter 368815 !
submitter 369646 !
submitter 369647 !
submitter 370068 !
submitter 372784 !
submitter 373589 !
submitter 373633 !
submitter 373718 !
submitter 374079 !
submitter 374080 !
submitter 374085 !
submitter 374137 !
submitter 374141 !
submitter 374440 !
submitter 375080 !
submitter 375789 !
submitter 376076 !
submitter 376129 !
submitter 376172 !
submitter 376811 !
submitter 377261 !
submitter 377564 !
submitter 378112 !
submitter 378406 !
submitter 378657 !
submitter 381038 !
submitter 381040 !
submitter 381042 !
submitter 381043 !
submitter 382324 !
submitter 382820 !
submitter 382824 !
submitter 383431 !
submitter 383962 !
submitter 383965 !
submitter 384412 !
submitter 384413 !
submitter 384574 !
submitter 391943 !
submitter 249212 !
submitter 308433 !

-- 
bye,
pabs

http://wiki.debian.org/PaulWise

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20070302152448.11317.52517.reportbug@rum.gielen.name>
BTS author: Casper Gielen <casper@zvdk.nl>

Package: debsecan
Version: 0.4.5
Followup-For: Bug #344117

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

It appears like this bug has returned:

#  su daemon -c '/usr/bin/debsecan --suite sid --mailto root --cron'

error: could not open '/var/lib/debsecan/history.new': Permission denied

# ls -al /var/lib/debsecan/
totaal 2
drwxr-xr-x  2 root root   48 2007-02-24 00:19 .
drwxr-xr-x 82 root root 2144 2007-02-28 22:55 ..


- -- System Information:
Debian Release: 4.0
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable'), (500, 'stable'), (1, 'experimental')
Architecture: i386 (i686)
Shell:  /bin/sh linked to /bin/bash
Kernel: Linux 2.6.17-2-686
Locale: LANG=nl_NL, LC_CTYPE=nl_NL (charmap=ISO-8859-15)

Versions of packages debsecan depends on:
ii  debconf [debconf-2.0]         1.5.11     Debian configuration management sy
ii  python                        2.4.4-2    An interactive high-level object-o
ii  python-apt                    0.6.19     Python interface to libapt-pkg

Versions of packages debsecan recommends:
ii  cron                          3.0pl1-100 management of regular background p
ii  exim4                         4.63-17    metapackage to ease exim MTA (v4) 
ii  exim4-daemon-heavy [mail-tran 4.63-17    exim MTA (v4) daemon with extended

- -- debconf information:
* debsecan/source:
* debsecan/mailto: root
* debsecan/suite: GENERIC
* debsecan/report: true

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.6 (GNU/Linux)

iD8DBQFF6EHAIhQIPPgOSvcRAj1qAJ9crMIk9AIu8Fz+okY81a/iVCARoQCdFBks
pKx5e6FkVS544TsL4XjUzJA=
=LxA/
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87649jej4w.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Casper Gielen:

> It appears like this bug has returned:
>
> #  su daemon -c '/usr/bin/debsecan --suite sid --mailto root --cron'
>
> error: could not open '/var/lib/debsecan/history.new': Permission denied
>
> # ls -al /var/lib/debsecan/
> totaal 2
> drwxr-xr-x  2 root root   48 2007-02-24 00:19 .
> drwxr-xr-x 82 root root 2144 2007-02-28 22:55 ..

Did this happen after an upgrade, or a fresh installation?  (You can
look into /var/log/dpkg.log to find out.)

I'm a bit mystified what could cause this.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1HNDta-0005CA-CN@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

# Automatically generated email from bts, devscripts version 2.9.27
found 344117 0.4.5

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1HNFMA-0004Sa-Cx@ries.debian.org>
BTS author: Florian Weimer <fw@deneb.enyo.de>

Source: debsecan
Source-Version: 0.4.6

We believe that the bug you reported is fixed in the latest version of
debsecan, which is due to be installed in the Debian FTP archive:

debsecan_0.4.6.dsc
  to pool/main/d/debsecan/debsecan_0.4.6.dsc
debsecan_0.4.6.tar.gz
  to pool/main/d/debsecan/debsecan_0.4.6.tar.gz
debsecan_0.4.6_all.deb
  to pool/main/d/debsecan/debsecan_0.4.6_all.deb



A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 344117@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Florian Weimer <fw@deneb.enyo.de> (supplier of updated debsecan package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.7
Date: Fri,  2 Mar 2007 21:58:39 +0100
Source: debsecan
Binary: debsecan
Architecture: source all
Version: 0.4.6
Distribution: unstable
Urgency: low
Maintainer: Florian Weimer <fw@deneb.enyo.de>
Changed-By: Florian Weimer <fw@deneb.enyo.de>
Description: 
 debsecan   - Debian Security Analyzer
Closes: 344117
Changes: 
 debsecan (0.4.6) unstable; urgency=low
 .
   * Migrate /var/lib/debsecan away from root permissions unconditionally.
     Closes: #344117 (again).
Files: 
 ba684ea13acf04c6cf34f84b847b8704 819 admin optional debsecan_0.4.6.dsc
 a5a300ae79246de7c0bb7b8e197583a4 83977 admin optional debsecan_0.4.6.tar.gz
 a367e561b9f5e6144191d62cb7360c9c 29838 admin optional debsecan_0.4.6_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.6 (GNU/Linux)

iQEVAwUBReiUVr97/wQC1SS+AQI9zwgAiVXjlf8pS4BXirHuZFG2l9/fywAsvOFo
ypQ1+y4tHTOHRGNwT1Pur9wqUKlD5t3TNxRAvObHlw8FQ3ceAvBRWfEwEVCrBaMh
VKZaq+IBkbNF6LuKy/0Ko0O3SS7ztBIARiVO7lqEiYd7lOPZ1NyL3gYXHOOZTU1y
9gucM+0M1RWu1igsrFpmMdcp26oexGYpUm0WIlJbaZFXWG/75DIPKaQCbscUGjrG
qnvYWD5VMchpUpLfdvxRJ3UkxKispXqtbmx9I0xoxJtcjSNuAZujQzheR2CgxpvP
CvrWdtAGp+yP0sUrSyVCj9GkVfpQniV9EsEP5nHEkLpOwZe/pr8t3g==
=LzO9
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A log time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
