### ISSUE TITLE
[787052] ParseError: expected package field

### ISSUE THREAD

**Issue by FedericoCeratto** [FedericoCeratto/debian-debsecan#92]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20150528064102.5598.63257.reportbug@I10005>
BTS author: =?utf-8?q?S=C3=A9bastien_KALT?= <skalt@throka.org>

Package: debsecan
Version: 0.4.18
Severity: normal

Dear Maintainer,

For some time now I have this error on my Sid laptop when launching debsecan
(the output is in the attached debsecan.txt file) :

$ debsecan --suite sid
[...]
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 1380, in <module>
    rate_system(target, options, fetch_data(options, config), history)
  File "/usr/bin/debsecan", line 1297, in rate_system
    for pkg in packages:
  File "/usr/bin/debsecan", line 131, in __iter__
    self.raiseSyntaxError("expected package field, got " + `line`)
  File "/usr/bin/debsecan", line 155, in raiseSyntaxError
    raise ParseError(self.name , lineno, msg)
__main__.ParseError: expected package field, got '#Vcs-Git:
git://git.debian.org/collab-maint/livret.git\n'

This error appeared on may 22.

Here are the packages upgraded on my machine this day :

Start-Date: 2015-05-22  20:48:58
Upgrade: ncurses-term:amd64 (5.9+20150516-1, 5.9+20150516-2), python-
distlib:amd64 (0.2.0-1, 0.2.0-2), libxapian22:amd64 (1.2.19-1, 1.2.21-1),
libtinfo5:amd64 (5.9+20150516-1, 5.9+20150516-2), tmux:amd64 (2.0-1, 2.0-2),
libassuan0:amd64 (2.2.0-2, 2.2.1-1), fuse:amd64 (2.9.3-15+b1, 2.9.3-16),
python-pkg-resources:amd64 (16.0-1, 16.0-2), python-wxgtk3.0:amd64
(3.0.1.1+dfsg-2, 3.0.2.0+dfsg-1), python-distlib-whl:amd64 (0.2.0-1, 0.2.0-2),
libncurses5:amd64 (5.9+20150516-1, 5.9+20150516-2), libharfbuzz-icu0:amd64
(0.9.40-2, 0.9.40-3), lightdm-gtk-greeter:amd64 (2.0.0-3, 2.0.1-1),
libanjuta-3-0:amd64 (3.14.0-1, 3.14.0-2), calendar-google-provider:amd64
(31.6.0-1, 31.7.0-1), libgudev-1.0-0:amd64 (215-17, 215-18), python-
setuptools:amd64 (16.0-1, 16.0-2), libncursesw5:amd64 (5.9+20150516-1,
5.9+20150516-2), ncurses-bin:amd64 (5.9+20150516-1, 5.9+20150516-2), libpam-
systemd:amd64 (215-17, 215-18), python3-pkg-resources:amd64 (16.0-1, 16.0-2),
iceowl-extension:amd64 (31.6.0-1, 31.7.0-1), udev:amd64 (215-17, 215-18),
libharfbuzz0b:amd64 (0.9.40-2, 0.9.40-3), icedove:amd64 (31.6.0-1, 31.7.0-1),
python3-distlib:amd64 (0.2.0-1, 0.2.0-2), libudev-dev:amd64 (215-17, 215-18),
libudev1:amd64 (215-17, 215-18), python-setuptools-whl:amd64 (16.0-1, 16.0-2),
python3-setuptools:amd64 (16.0-1, 16.0-2), systemd-sysv:amd64 (215-17, 215-18),
systemd:amd64 (215-17, 215-18), anjuta-common:amd64 (3.14.0-1, 3.14.0-2),
libclone-perl:amd64 (0.37-1+b1, 0.38-1), libsystemd0:amd64 (215-17, 215-18),
libfuse2:amd64 (2.9.3-15+b1, 2.9.3-16), python-wxversion:amd64 (3.0.1.1+dfsg-2,
3.0.2.0+dfsg-1), ncurses-base:amd64 (5.9+20150516-1, 5.9+20150516-2)
End-Date: 2015-05-22  20:53:32

Start-Date: 2015-05-22  20:56:34
Install: librpmsign3:amd64 (4.12.0.1+dfsg1-2, automatic)
Upgrade: rpm2cpio:amd64 (4.11.3-1.1, 4.12.0.1+dfsg1-2), rpm-common:amd64
(4.11.3-1.1, 4.12.0.1+dfsg1-2), rpm:amd64 (4.11.3-1.1, 4.12.0.1+dfsg1-2),
librpm3:amd64 (4.11.3-1.1, 4.12.0.1+dfsg1-2), debugedit:amd64 (4.11.3-1.1,
4.12.0.1+dfsg1-2), librpmbuild3:amd64 (4.11.3-1.1, 4.12.0.1+dfsg1-2),
librpmio3:amd64 (4.11.3-1.1, 4.12.0.1+dfsg1-2)
Remove: librpmsign1:amd64 (4.11.3-1.1)
End-Date: 2015-05-22  20:56:52

And the day before :

Start-Date: 2015-05-21  22:13:39
Upgrade: initscripts:amd64 (2.88dsf-59.1, 2.88dsf-59.2), ncurses-term:amd64
(5.9+20140913-1, 5.9+20150516-1), sysvinit:amd64 (2.88dsf-59.1, 2.88dsf-59.2),
libblkid-dev:amd64 (2.26.2-3, 2.26.2-4), libtinfo5:amd64 (5.9+20140913-1+b1,
5.9+20150516-1), libgnutls-openssl27:amd64 (3.3.14-2, 3.3.15-2),
libsqlite3-dev:amd64 (3.8.10.1-1, 3.8.10.2-1), python-pkg-resources:amd64
(5.5.1-1, 16.0-1), libgnutls-deb0-28:amd64 (3.3.14-2, 3.3.15-2),
libncurses5:amd64 (5.9+20140913-1+b1, 5.9+20150516-1), util-linux-locales:amd64
(2.26.2-3, 2.26.2-4), chromium-l10n:amd64 (42.0.2311.135-2, 43.0.2357.65-1),
libsmartcols1:amd64 (2.26.2-3, 2.26.2-4), uuid-dev:amd64 (2.26.2-3, 2.26.2-4),
mount:amd64 (2.26.2-3, 2.26.2-4), python-setuptools:amd64 (5.5.1-1, 16.0-1),
libncursesw5:amd64 (5.9+20140913-1+b1, 5.9+20150516-1), ncurses-bin:amd64
(5.9+20140913-1+b1, 5.9+20150516-1), postgresql-common:amd64 (167, 168),
python3-pkg-resources:amd64 (5.5.1-1, 16.0-1), libuuid1:amd64 (2.26.2-3,
2.26.2-4), libmount1:amd64 (2.26.2-3, 2.26.2-4), libcaribou0:amd64 (0.4.15-1,
0.4.18.1-1), chromium:amd64 (42.0.2311.135-2, 43.0.2357.65-1), sqlite3:amd64
(3.8.10.1-1, 3.8.10.2-1), libfdisk1:amd64 (2.26.2-3, 2.26.2-4), baobab:amd64
(3.14.1-1, 3.16.1-1), libsqlite3-0:amd64 (3.8.10.1-1, 3.8.10.2-1),
gir1.2-caribou-1.0:amd64 (0.4.15-1, 0.4.18.1-1), jhead:amd64 (2.97-1, 3.00-1),
gpodder:amd64 (3.8.3-1, 3.8.3-2), bsdutils:amd64 (2.26.2-3, 2.26.2-4),
libdvdnav4:amd64 (5.0.1-1, 5.0.1-4), uuid-runtime:amd64 (2.26.2-3, 2.26.2-4),
python-setuptools-whl:amd64 (5.5.1-1, 16.0-1), python3-setuptools:amd64
(5.5.1-1, 16.0-1), sysv-rc:amd64 (2.88dsf-59.1, 2.88dsf-59.2), sysvinit-
utils:amd64 (2.88dsf-59.1, 2.88dsf-59.2), libblkid1:amd64 (2.26.2-3, 2.26.2-4),
postgresql-doc:amd64 (9.4+167, 9.4+168), postgresql-client:amd64 (9.4+167,
9.4+168), util-linux:amd64 (2.26.2-3, 2.26.2-4), libcaribou-common:amd64
(0.4.15-1, 0.4.18.1-1), ncurses-base:amd64 (5.9+20140913-1, 5.9+20150516-1),
postgresql-contrib:amd64 (9.4+167, 9.4+168), postgresql-client-common:amd64
(167, 168), sqlite3-doc:amd64 (3.8.10.1-1, 3.8.10.2-1), postgresql:amd64
(9.4+167, 9.4+168)
End-Date: 2015-05-21  22:17:37

Regards

Sébastien KALT


-- System Information:
Debian Release: stretch/sid
  APT prefers unstable
  APT policy: (980, 'unstable'), (970, 'testing'), (960, 'stable')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.0.0-4.slh.1-aptosid-amd64 (SMP w/4 CPU cores; PREEMPT)
Locale: LANG=fr_FR.UTF-8, LC_CTYPE=fr_FR.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages debsecan depends on:
ii  ca-certificates        20141019
ii  debconf [debconf-2.0]  1.5.56
ii  python                 2.7.9-1
ii  python-apt             0.9.4

Versions of packages debsecan recommends:
ii  cron                            3.0pl1-128
ii  postfix [mail-transport-agent]  2.11.3-1

debsecan suggests no packages.

-- debconf information:
  debsecan/source:
  debsecan/suite: GENERIC

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <87siaf72bk.fsf@mid.deneb.enyo.de>
BTS author: Florian Weimer <fw@deneb.enyo.de>

* Sébastien KALT:

> For some time now I have this error on my Sid laptop when launching debsecan
> (the output is in the attached debsecan.txt file) :
>
> $ debsecan --suite sid
> [...]
> Traceback (most recent call last):
>   File "/usr/bin/debsecan", line 1380, in <module>
>     rate_system(target, options, fetch_data(options, config), history)
>   File "/usr/bin/debsecan", line 1297, in rate_system
>     for pkg in packages:
>   File "/usr/bin/debsecan", line 131, in __iter__
>     self.raiseSyntaxError("expected package field, got " + `line`)
>   File "/usr/bin/debsecan", line 155, in raiseSyntaxError
>     raise ParseError(self.name , lineno, msg)
> __main__.ParseError: expected package field, got '#Vcs-Git:
> git://git.debian.org/collab-maint/livret.git\n'
>
> This error appeared on may 22.

I don't see this in the Packages files for sid.  Can you grep for the
string "livret" in your /var/lib/dpkg/status file and show the
surrounding package entry?

The debsecan error message is certainly worthy of improvement, but
there isn't much debsecan do if this file does not match the expected
syntax.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <CAN64BFZdVQLRkEPj3ozhZfy-411FbfrDFk-nXDFUh7FCenh55A@mail.gmail.com>
BTS author: =?UTF-8?Q?S=C3=A9bastien_Kalt?= <skalt@throka.org>

Hi Florian,

2015-05-29 18:53 GMT+02:00 Florian Weimer <fw@deneb.enyo.de>:

> * Sébastien KALT:
>
> > For some time now I have this error on my Sid laptop when launching
> debsecan
> > (the output is in the attached debsecan.txt file) :
> >
> > $ debsecan --suite sid
> > [...]
> > Traceback (most recent call last):
> >   File "/usr/bin/debsecan", line 1380, in <module>
> >     rate_system(target, options, fetch_data(options, config), history)
> >   File "/usr/bin/debsecan", line 1297, in rate_system
> >     for pkg in packages:
> >   File "/usr/bin/debsecan", line 131, in __iter__
> >     self.raiseSyntaxError("expected package field, got " + `line`)
> >   File "/usr/bin/debsecan", line 155, in raiseSyntaxError
> >     raise ParseError(self.name , lineno, msg)
> > __main__.ParseError: expected package field, got '#Vcs-Git:
> > git://git.debian.org/collab-maint/livret.git\n'
> >
> > This error appeared on may 22.
>
> I don't see this in the Packages files for sid.  Can you grep for the
> string "livret" in your /var/lib/dpkg/status file and show the
> surrounding package entry?
>
This package was installed from a .deb downloaded from the developper's
website, so it's not included in Debian archives.

So it's not a bug, it's a problem with the package.


> The debsecan error message is certainly worthy of improvement, but
> there isn't much debsecan do if this file does not match the expected
> syntax.
>
I'll forward the information to the developper.

I'm sorry for the false report.

Regards,

Sébastien

**Comment by FedericoCeratto** [comment]
BTS_msg_id: Bug archived.
BTS author: Debbugs Internal Request <owner@bugs.debian.org>

# A New Hope
# A long time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
